[package]
name = "turnip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
battery = "0.7.8"
sysinfo = "0.30.13"
tokio = { version = "1.39.2", features = ["full"] }